export const POKEMON_TRAINER_CREATE_REQUEST = 'POKEMON_TRAINER_CREATE_REQUEST'
export const POKEMON_TRAINER_CREATE_SUCCESS = 'POKEMON_TRAINER_CREATE_SUCCESS'
export const POKEMON_TRAINER_CREATE_ERROR = 'POKEMON_TRAINER_CREATE_ERROR'

export const POKEMON_TRAINER_UPDATE_REQUEST = 'POKEMON_TRAINER_UPDATE_REQUEST'
export const POKEMON_TRAINER_UPDATE_SUCCESS = 'POKEMON_TRAINER_UPDATE_SUCCESS'
export const POKEMON_TRAINER_UPDATE_ERROR = 'POKEMON_TRAINER_UPDATE_ERROR'

export const POKEMON_TRAINER_GET_REQUEST = 'POKEMON_TRAINER_GET_REQUEST'
export const POKEMON_TRAINER_GET_SUCCESS = 'POKEMON_TRAINER_GET_SUCCESS'
export const POKEMON_TRAINER_GET_ERROR = 'POKEMON_TRAINER_GET_ERROR'
